version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: HOLB_TON

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
    - "8080:80"
    depends_on:
    - db